# Biological data

## Taxonomy

The Register of Antarctic Marine Species (RAMS) is the authoritative taxonomic database for Antarctic marine organisms. RAMS is part of the World Register of Marine Species (WoRMS).

- [worrms](https://cran.r-project.org/package=worrms) client for the [WoRMS](http://www.marinespecies.org/) API. Contains mostly taxonomic data, but also trait data.
- [taxize](https://cran.r-project.org/package=taxize) provides access to 20ish sources of taxonomic data sources, including WoRMS. It has consistent data outputs and function interfaces across the different data sources so that you don't need to tailor your code to different taxonomic data providers.

RAMS is currently being extended to cover non-marine taxa, which will become the Register of Antarctic Species (RAS). Hopefully this will remain covered by `worrms` and the server-side infrastructure hosted by VLIZ.

For more detail on R packages dealing with taxonomy in general, see the [rOpenSci taxonomy task view](https://github.com/ropensci/taxonomy).

## Other packages

Tracking of animals using satellite, GPS, or light-level geolocation tags is common, and there are many R packages that can help with this. See the [spatiotemporal task view](https://cloud.r-project.org/web/views/SpatioTemporal.html) for a more complete list. Also of interest may be:

- [TwilightFree](https://github.com/ABindoff/TwilightFree) provides a method for processing light-level geolocation data that is robust to noise (sensor shading and obscuration) and may be particularly suitable for Southern Ocean applications.

- [traipse](https://github.com/Trackage/traipse) provides tools for tracking data, for common metrics of distance, direction, and speed.

- [foieGras](https://github.com/ianjonsen/foieGras) fits a continuous-time model (RW or CRW) in state-space form to filter Argos satellite location data.
